# Minimal TOML configuration for bootc-image-builder (with systemd masking)

# Load required kernel modules on boot
[[customizations.files]]
path = "/etc/modules-load.d/kubernetes.conf"
mode = "0644"
contents = """
overlay
br_netfilter
"""

# Persist sysctl kernel parameters
[[customizations.files]]
path = "/etc/sysctl.d/99-kubernetes.conf"
mode = "0644"
contents = """
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv4.tcp_congestion_control = bbr
vm.overcommit_memory = 1
kernel.panic = 10
kernel.panic_on_oops = 1
fs.inotify.max_user_instances = 8192
fs.inotify.max_user_watches = 524288
"""

# Set transparent hugepages behavior
[customizations.kernel]
append = "transparent_hugepage=madvise"

# Disable swap via a systemd service
[[customizations.files]]
path = "/etc/systemd/system/disable-swap.service"
mode = "0644"
contents = """
[Unit]
Description=Disable swap at boot
Before=local-fs.target

[Service]
Type=oneshot
ExecStart=/sbin/swapoff -a

[Install]
WantedBy=multi-user.target
"""

# Enable auditd and disable-swap using symlinks
[[customizations.directories]]
path = "/etc/systemd/system/multi-user.target.wants"
mode = "0755"

[[customizations.files]]
path = "/etc/systemd/system/multi-user.target.wants/disable-swap.service"
target = "/etc/systemd/system/disable-swap.service"
type = "symlink"

[[customizations.files]]
path = "/etc/systemd/system/multi-user.target.wants/auditd.service"
target = "/usr/lib/systemd/system/auditd.service"
type = "symlink"

# Mask conntrackd.service to disable it completely
[[customizations.files]]
path = "/etc/systemd/system/conntrackd.service"
target = "/dev/null"
type = "symlink"

# Kickstart section for Anaconda ISO installation
[customizations.installer.kickstart]
contents = """
text --non-interactive

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'

# System language
lang en_US.UTF-8

# Root password
rootpw --iscrypted $6$D/XHYcNVecS4Epno$gICwU.NzAUGECDn6sJhDsDTcjaYiylDdtGWQZPpgELNxCU8kp7DZnhyITKWYZNrxzZmjGcnT5wuLVJRSPCEjY1
user --name=builder --groups=wheel --password=password --plaintext

# System services
selinux --permissive
firewall --disabled
services --enabled=\"NetworkManager,sshd,chronyd,kubelet,containerd\"

zerombr
clearpart --all --initlabel --disklabel=gpt
autopart --noswap --type=lvm
network --bootproto=dhcp --device=link --activate --onboot=on

%addon com_redhat_kdump --disable
%end
"""
