name = "AlmaLinux 10 Kube OS"
description = "AlmaLinux 10 with Kubernetes tools"
version = "10.0"
distro = "almalinux-10"

[customizations.kernel]
# name - not yet supported
append = "transparent_hugepage=madvise"

[customizations.timezone]
timezone = "US/Eastern"
ntpservers = ["time.nist.gov"]

[customizations.services]
enabled = ["auditd", "vmtoolsd"]
masked = ["conntrackd"]

[customizations.installer.kickstart]
contents = """
#version=RHEL9
# Use text mode install
text
# Keyboard layouts
keyboard 'us'
# System language
lang en_US.UTF-8
# System timezone
timezone America/New_York --utc
# Accept the EULA
eula --agreed

# Network information
network  --bootproto=dhcp --device=link --activate --onboot=on

# Disk partitioning information
zerombr
clearpart --all --initlabel --disklabel=gpt --drives=sda
part /boot/efi --fstype="efi" --size=500 --label="EFIFS"
part /boot --fstype="xfs" --size=500 --label="BOOTFS"
part pv.01 --fstype="lvmpv" --grow --size=1

volgroup sysvg pv.01

logvol /          --vgname=sysvg --name=ROOTFS        --size=20480 --fstype=xfs 
logvol /var       --vgname=sysvg --name=VARFS         --size=20480 --fstype=xfs 
logvol /var/log   --vgname=sysvg --name=VARLOGFS      --size=4096  --fstype=xfs 
logvol /var/log/audit --vgname=sysvg --name=VARLOGAUDITFS --size=10240 --fstype=xfs 
logvol /home      --vgname=sysvg --name=HOMEFS        --size=1024  --fstype=xfs 
logvol /tmp       --vgname=sysvg --name=TMPFS         --size=8192  --fstype=xfs
logvol /var/tmp   --vgname=sysvg --name=VARTMPFS      --size=8192  --fstype=xfs

# User configuration for the installer
user --name=kubeadmin --groups=wheel --password="$6$pubJxDw2EWMDmvva$q9nwd6wDhazD0pkX63IuBXLMThHNnEGkwLFzLYNjaEoVwzPvt4jEV1KNm9lua44OY3.sSgKv75.hqtKfFLNv//" --iscrypted

# Reboot after installation
reboot
"""
